# Generated by Django 5.0.9 on 2024-12-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_country_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
    ]
